# Data directory
data_dir: ./data


# Embedding
fast_embed_name: BAAI/bge-small-en-v1.5
embedding_cache_dir: ./cache
embedding_batch_size: 128
embedding_save_every: 512
embedding_save_checkpoints: false
embeddings_file_name: all_messages_embeddings.npy


# Pinecone configuration
pc_index: simple-nlp
pc_cloud: aws
pc_region: us-east-1
pinecone_batch_size: 100
distance_metric: cosine

# Retrieval configuration
qa_top_k: 50
ner_model: en_core_web_md
ner_model_version: "3.7.0"
ner_model_storage_dir: ./runtime_models/spacy